"""A small, varied probe corpus. Activations are only as good as the inputs
that produce them, so it mixes prose, arithmetic, code, lists and dialogue."""

CORPUS = [
    "Alice has three apples and gets two more, so now she has five apples in her basket.",
    "The mitochondria convert glucose and oxygen into ATP through a chain of redox reactions.",
    "def add(a, b):\n    return a + b\n\nprint(add(3, 4))",
    "In 1905 Einstein published four papers that changed how physicists think about light, time and matter.",
    "The recipe calls for two cups of flour, one egg, a pinch of salt and half a cup of milk.",
    "Seven times eight is fifty-six, and fifty-six divided by four is fourteen.",
    "She closed the laptop, looked out at the rain, and decided the email could wait until morning.",
    "SELECT name, price FROM products WHERE price > 100 ORDER BY price DESC;",
    "Photosynthesis uses light energy to turn carbon dioxide and water into sugar and oxygen.",
    "The capital of France is Paris, and the capital of Japan is Tokyo.",
    "If it rains tomorrow, the match will be moved to Sunday; otherwise it starts at noon.",
    "A prime number has exactly two divisors: one and itself. The first few are 2, 3, 5, 7 and 11.",
    "for i in range(10):\n    if i % 2 == 0:\n        print(i)",
    "The river flooded the lower village, but the bridge built by the old engineers held firm.",
    "Customer: my order arrived damaged. Agent: I'm sorry, I can send a replacement today.",
    "Water boils at one hundred degrees Celsius at sea level, but at a lower temperature on a mountain.",
    "The quick brown fox jumps over the lazy dog while the cat watches from the fence.",
    "Inflation rose to four percent last quarter, prompting the central bank to raise interest rates.",
    "Neurons communicate through synapses, releasing neurotransmitters that bind to receptors.",
    "To reverse a list in Python you can write items[::-1] or call items.reverse().",
    "The fuel station sold 4,200 litres of diesel on Monday and 3,850 litres on Tuesday.",
    "Once upon a time, a small bird built her nest in the branches of an old oak tree.",
    "Every even number greater than two is conjectured to be the sum of two primes.",
    "The meeting is at 3:30 pm in room 204; please bring the quarterly sales report.",
    "Gravity pulls objects toward each other in proportion to their masses.",
    "He said he would call back, but the phone stayed silent all evening.",
    "The derivative of x squared is two x, and the integral of two x is x squared plus a constant.",
    "Wholesale prices for rice and lentils increased after the monsoon damaged the harvest.",
    "const total = items.reduce((sum, item) => sum + item.price, 0);",
    "The museum's new exhibit features pottery from ancient Mesopotamia and Egypt.",
    "Enzymes lower the activation energy of reactions without being consumed themselves.",
    "Ten minus three is seven. Seven plus nine is sixteen. Sixteen is four squared.",
    "The train left the station at dawn, crossing fields that were still white with frost.",
    "An API returns a 404 status code when the requested resource cannot be found.",
    "Shakespeare wrote Hamlet around 1600, and it remains one of his most performed plays.",
    "The children built a sandcastle, and the tide slowly washed its walls away.",
    "Insulin lets cells absorb glucose from the blood, lowering blood sugar levels.",
    "git commit -m 'fix off-by-one error in pagination'",
    "The mountain trail is steep but the view from the summit makes the climb worthwhile.",
    "A triangle's angles always add up to one hundred and eighty degrees.",
    "Please confirm the delivery address: 42 Lake Road, Springfield, before we ship the order.",
    "The violinist played the final note and the hall fell completely silent.",
    "Carbon has four valence electrons, which is why it forms so many different compounds.",
    "If x plus five equals twelve, then x equals seven.",
    "The startup grew from two founders to forty employees in under three years.",
    "Bees communicate the location of flowers to the hive with a waggle dance.",
    "while queue:\n    node = queue.pop(0)\n    visited.add(node)",
    "The detective noticed that the clock had stopped at exactly ten past nine.",
    "Sound travels faster in water than in air because water molecules are packed more closely.",
    "One kilometre is a thousand metres, and one metre is a hundred centimetres.",
    "The negotiations stalled when neither side would accept the proposed deadline.",
    "Fatty acids are broken down in the mitochondria through beta-oxidation.",
    "The old library smelled of dust and paper, and the floorboards creaked underfoot.",
    "A hash map gives average constant-time lookups by storing keys in buckets.",
    "Twelve eggs make a dozen, so three dozen eggs is thirty-six eggs.",
    "The volcano had been dormant for centuries before the sudden eruption last spring.",
    "Thank you for your patience; your refund has been processed and should arrive in five days.",
    "The Pythagorean theorem states that a squared plus b squared equals c squared.",
    "Snow fell all night, and by morning the whole city was quiet and white.",
    "Vaccines train the immune system to recognise a pathogen before a real infection.",
    "The inventory shows 120 cartons of cooking oil and 75 sacks of sugar in the godown.",
    "She solved the puzzle by working backwards from the final square.",
    "Light from the Sun takes about eight minutes to reach the Earth.",
    "import numpy as np\nx = np.linspace(0, 1, 100)\ny = np.sin(2 * np.pi * x)",
]
